### ISSUE TITLE
为什么机器人的答复有问题

### ISSUE THREAD

**Issue by Arturia169** [MeetWq/nonebot-plugin-asoulcnki#4]
![image](https://user-images.githubusercontent.com/69199123/169455472-9617b032-d583-4d3e-9fd8-844a28cec7b8.png)

**Comment by MeetWq** [comment]
需要系统中有中文字体

**Comment by Arturia169** [comment]
安装一个中文字体就行了吗

**Comment by Arturia169** [comment]
![image](https://user-images.githubusercontent.com/69199123/169467222-77745b7d-1cfe-422a-817d-94d7dc2a7f14.png)
已解决 安装中文字体
